language: java
jdk:
  - oraclejdk9
cache:
  directories:
    - $HOME/.gradle
before_script:
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle wrapper
script:
  - ./gradle wrapper check
  - ./gradle wrapper install -x check
  - ./gradle wrapper codeCoverageReport --continue