language: java
services:
  - mysql
jdk:
  - oraclejdk9
dist: precise
before_install:
  - sudo mysql -e 'CREATE DATABASE AgileTasks_DB;'
  - sudo mysql -e 'select database();'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE AgileTasks_DB; select database();'
  - sudo mysql --version
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle wrapper
  - pip install --user codecov
test:
  adapter: mysql2
    database: AgileTasks_DB
    username: root
    encoding: utf8
script:
  - gradle check
after_success:
  - codecov --file coverage/lcov.info --disable search
