language: java
services:
  - mysql
jdk:
  - oraclejdk9
before_install:
  - sudo mysql -e 'CREATE DATABASE AgileTasks_DB;'
  - sudo mysql -e 'select database();'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE AgileTasks_DB; select database();'
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle wrapper
  - pip install --user codecov
before_script:
  - sudo mysql -u root -e "USE mysql; UPDATE user SET password=PASSWORD('root') WHERE user='root'; FLUSH PRIVILEGES;" |
script:
  - gradle check
after_success:
  - codecov --file coverage/lcov.info --disable search
