language: java
services:
  - mysql
jdk:
  - oraclejdk9
before_install:
  - sudo mysql -e 'CREATE DATABASE AgileTasks_DB;'
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle wrapper
  - pip install --user codecov
script:
  - gradle check
after_success:
  - codecov --file coverage/lcov.info --disable search
